AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 30


Resources:

    WebhookotronFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: build/
            Handler: app.lambda_handler
            Runtime: python2.7
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                Webhookotron:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /webhook
                        Method: post
            Policies:
                # XXX: Find out how to restrict this to put to a specific bucket
                # E.g.: based on https://docs.aws.amazon.com/lambda/latest/dg/policy-templates.html
                # How to do we put that kind of policy into this file?
                - AmazonS3FullAccess

Outputs:

    WebhookotronApi:
      Description: "API Gateway endpoint URL for Prod stage for Webhookotron function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"

    WebhookotronFunction:
      Description: "Webhookotron Lambda Function ARN"
      Value: !GetAtt WebhookotronFunction.Arn

    WebhookotronFunctionIamRole:
      Description: "Implicit IAM Role created for Webhookotron function"
      Value: !GetAtt WebhookotronFunctionRole.Arn
